In [1]:
import numpy as np
import os 
import gc

In [2]:
##### Function to Extract data from .txt files
def data_extractor(txt_file_path):
    """
       Function to extract time series data 
       from a .txt file
    """
    #### Reading File
    line_list = []
    with open(txt_file_path, 'r') as reader:
    
    # Read and print the entire file line by line
        line = reader.readline()
        while line != '':  # The EOF char is an empty string
            #print(line, end='')
            line_list.append(line)
            line = reader.readline()

    #### Taking the Time Step Data
    ##line_list = line_list[1:]

    #### Splitting the Collected Text Strings and Converting them into Floating type values
    new_list = []
    for item in line_list:
        sub_list = []
        for sub_item in item.split():
            sub_list.append(float(sub_item))
        new_list.append(sub_list)
    ### Deleting Extrass
    del(line_list)
    gc.collect()
    


    trimmed_list = []
    for j in range(5000,105000):
            trimmed_list.append(new_list[j])
    ### Deleting Extrass
    del(new_list)
    gc.collect()

    
    #### Extracting Final parameters [latitude, longitude, velocity in x, velocity in y]
    final_list = []
    for item in trimmed_list:
        final_list.append([item[0],item[1],item[2], item[3]])
    ### Deleting Extraas
    del(trimmed_list)
    gc.collect()
    
    ### Returning the feature extracted list as numpy array
    return np.array(final_list)

In [5]:
### Enter relative path of folder containing all the .txt files
dir = 'KITTI_datasets\\2011_09_26\\2011_09_26_drive_0002_extract\\velodyne_points\\data'

### Creating list to contain data
X  = []
for file_path in np.sort(os.listdir(dir)):
  file_path_final = os.path.join(dir,file_path)
  X.append(data_extractor(file_path_final))

### Converting list to numpy array
X = np.array(X)

### Reshaping
print(X.shape)

### creating single npz data file
np.savez_compressed('Dataset_Extractor\\2_bicyclist_data.npz',X)

### Loading numpy array to variable 
measurements = np.load('Dataset_Extractor\\2_bicyclist_data.npz', allow_pickle=True)['arr_0']
print(measurements)

(80, 100000, 4)
[[[ 6.3518e+01  4.6254e+01  1.4030e+00  1.5000e-01]
  [ 6.3466e+01  4.6522e+01  1.4050e+00  0.0000e+00]
  [ 6.3392e+01  4.6774e+01  1.4060e+00  0.0000e+00]
  ...
  [ 4.9040e+00  1.0110e+00 -1.6780e+00  4.0000e-02]
  [ 4.8960e+00  1.0260e+00 -1.6760e+00  3.0000e-02]
  [ 4.9000e+00  1.0430e+00 -1.6780e+00  4.0000e-02]]

 [[ 6.7053e+01  3.3202e+01  1.3460e+00  0.0000e+00]
  [ 5.4466e+01  2.9581e+01  1.1510e+00  0.0000e+00]
  [ 5.4299e+01  2.9712e+01  1.1490e+00  0.0000e+00]
  ...
  [ 5.1330e+00 -9.2000e-02 -1.6810e+00  4.0000e-02]
  [ 5.1430e+00 -7.6000e-02 -1.6840e+00  8.0000e-02]
  [ 5.1470e+00 -6.8000e-02 -1.6850e+00  8.0000e-02]]

 [[ 4.2238e+01  2.7255e+01  9.7200e-01  1.0000e-01]
  [ 4.2040e+01  2.7314e+01  9.7000e-01  9.0000e-02]
  [ 4.1909e+01  2.7417e+01  9.7000e-01  0.0000e+00]
  ...
  [ 5.0810e+00  2.7500e-01 -1.7070e+00  4.0000e-02]
  [ 5.0860e+00  2.9100e-01 -1.7090e+00  4.0000e-02]
  [ 5.0760e+00  2.9900e-01 -1.7050e+00  3.0000e-02]]

 ...

 [[ 1.6295e+01  2.

In [4]:
#convert the raw image sequence to video for viz

import cv2
import os

image_folder = 'KITTI_datasets\\2011_09_26\\2011_09_26_drive_0002_extract\\image_02\\data'
video_name = 'video_0002.avi'

images = [img for img in os.listdir(image_folder) if img.endswith(".png")]
frame = cv2.imread(os.path.join(image_folder, images[0]))
height, width, layers = frame.shape

video = cv2.VideoWriter(video_name, 0, 10, (width,height))

for image in images:
    video.write(cv2.imread(os.path.join(image_folder, image)))

cv2.destroyAllWindows()
video.release()